# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=255)),
                ('value', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Heritage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
                ('title', models.TextField(max_length=255)),
                ('description', models.TextField()),
                ('annotationCount', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Multimedia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('image', 'image'), ('location', 'location')], max_length=10)),
                ('url', models.URLField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='multimedia', to='heritages.Heritage')),
            ],
        ),
        migrations.CreateModel(
            name='Origin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('heritage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin', to='heritages.Heritage')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='heritage',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='heritages.Tag'),
        ),
        migrations.AddField(
            model_name='basicinformation',
            name='heritage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basicInformation', to='heritages.Heritage'),
        ),
    ]
