# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='multimedia',
            name='meta',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
