# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 18:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('heritages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True,
                                        serialize=False,
                                        verbose_name='ID')),
                ('date_of_birth', models.DateField(null=True,
                                                   verbose_name='Date of Birth')),
                ('note', models.TextField(blank=True,
                                          null=True,
                                          verbose_name='Notes')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE,
                                              related_name='profile',
                                              to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
