# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0002_multimedia_meta'),
    ]

    operations = [
        migrations.AddField(
            model_name='heritage',
            name='endDate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritage',
            name='exactDate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='heritage',
            name='startDate',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
