# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0004_auto_20170519_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='endDate',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='exactDate',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='startDate',
            field=models.TextField(default='', null=True),
        ),
    ]
