# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-19 12:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0005_auto_20170519_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='heritage',
            name='endDate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='exactDate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='startDate',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='heritage',
            name='tags',
            field=models.ManyToManyField(null=True, related_name='tags', to='heritages.Tag'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='file',
            field=models.FileField(blank=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='meta',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='multimedia',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
