# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0006_auto_20170501_2020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
