# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heritages', '0004_annotation_annotationbody_annotationtarget_selector'),
        ('heritages', '0008_auto_20170501_2057'),
        ('heritages', '0007_auto_20170519_1306'),
    ]

    operations = [
    ]
